### ISSUE TITLE
Checkins not being synced after successful test/setup

### ISSUE THREAD

**Issue by raucao** [diplix/OwnYourCheckin#9]
First of all, thanks for setting this up!

Unfortunately, it's currently not running correctly it seems. I configured my site yesterday, and everything was green and the test post worked fine. But since then, no checkins had been synced. So I configured it again, also with the test post working, but I'm still not getting checkins synced automatically.

I would assume it's probably not a bug in the code, but sth like a worker not running on the server. Anyway, opening this issue to let you know.

**Comment by diplix** [comment]
yeah. looks like the worker was down. sorry for that, i restarted the worker and there seems to be some activity now, probably working the queue. however, i saw some errors and other problems in the logs, too. since i’ll not be able to fix those in this forked repo of @aaronpk’s ownyourgram and since aaron did the same as ownyourgram in https://ownyourswarm.p3k.io, i rocommend to switch over to aaron’s implementation. also, because it’s much better done and maintained.

**Comment by raucao** [comment]
Ok, thanks.

How can I delete the integration for my site?

**Comment by diplix** [comment]
i don’t know :(
but i just deleted your data. that should stop pushing your swarm/4sq data to your site..

<img width="426" alt="bildschirmfoto 2017-06-27 um 09 04 29" src="https://user-images.githubusercontent.com/4541494/27574776-f3feeb0c-5b17-11e7-8928-84f64b28549d.png">

**Comment by raucao** [comment]
Great, thanks!

![thanks-ht](https://user-images.githubusercontent.com/842/27613079-6ffc0006-5b4e-11e7-8c4f-eb25a3ba74dc.gif)
